#!/bin/sh

#SBATCH --job-name=eff
#SBATCH --qos=avery
#SBATCH --account=avery
#SBATCH --time=4:00:00
#SBATCH --partition=hpg-dev
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8GB
#SBATCH --output=slurm_output/slurm-%A_%a.out

# sbatch scripts/feynnet/efficiencies/run

random_number=$RANDOM

mkdir -p tmp

cfg="tmp/feynnet_$random_number.cfg"
cp config/feynnet.cfg $cfg
python scripts/feynnet/efficiencies/print_config.py --config $cfg

sh scripts/feynnet/efficiencies/submitEfficienciesToSLURM.sh $cfg

python scripts/feynnet/efficiencies/plot_efficiencies.py --config $cfg

rm -r $cfg
rm tmp/*$random_number*