import matplotlib as mpl

Mine = {
    "font.sans-serif": ["DejaVu Sans"],
    "font.family": "sans-serif",
    "font.family": "serif",
    "font.size": 22,
    "mathtext.fontset": "custom",
    "mathtext.rm": "sans-serif",
    "mathtext.bf": "Helvetica:bold",
    "mathtext.sf": "Helvetica",
    "mathtext.it": "Helvetica:italic",
    "mathtext.tt": "Helvetica",
    "mathtext.cal": "Helvetica",
    "mathtext.default": "regular",
    "figure.figsize": (10.0, 6.0),
    "axes.titlesize": "medium",
    "axes.labelsize": "medium",
    "axes.unicode_minus": False,
    "axes.linewidth": 2,
    "axes.formatter.limits: ": (-2, 2),
    "axes.formatter.use_mathtext": True,
    "axes.formatter.min_exponent": 0,
    "axes.formatter.useoffset": True,
    "axes.formatter.offset_threshold": 3,
    "grid.alpha": 0.8,
    "grid.linestyle": ":",
    "line.linewidth": "2",
    "legend.fontsize": "small",
    "legend.handlelength": 1.5,
    "legend.borderpad": 0.5,
    "legend.frameon": False,
    "xaxis.labellocation": "right",
    "xtick.labelsize": "small",
    "xtick.direction": "in",
    "xtick.major.size": 12,
    "xtick.minor.size": 6,
    "xtick.major.pad": 6,
    "xtick.top": True,
    "xtick.top": True,
    "xtick.major.top": True,
    "xtick.major.bottom": True,
    "xtick.minor.top": True,
    "xtick.minor.bottom": True,
    "xtick.minor.visible": True,
    "xtick.minor.visible": True,
    "yaxis.labellocation": "top",
    "ytick.labelsize": "small",
    "ytick.direction": "in",
    "ytick.major.size": 12,
    "ytick.minor.size": 6.0,
    "ytick.right": True,
    "ytick.major.left": True,
    "ytick.major.right": True,
    "ytick.minor.left": True,
    "ytick.minor.right": True,
    "ytick.minor.visible": True,
    "savefig.transparent": False,
    "savefig.bbox": 'tight',
}

lotsa_plots = {
    "font.sans-serif": ["DejaVu Sans"],
    "font.family": "sans-serif",
    "mathtext.fontset": "custom",
    # "mathtext.rm": "Helvetica",
    # "mathtext.bf": "Helvetica:bold",
    # "mathtext.sf": "Helvetica",
    # "mathtext.it": "Helvetica:italic",
    # "mathtext.tt": "Helvetica",
    # "mathtext.cal": "Helvetica",
    "mathtext.default": "regular",
    "figure.figsize": (10.0, 10.0),
    "font.size": 16,
    "axes.labelsize": "medium",
    "axes.unicode_minus": False,
    "xtick.labelsize": "small",
    "ytick.labelsize": "small",
    "legend.fontsize": "small",
    "legend.handlelength": 1.5,
    "legend.borderpad": 0.5,
    "legend.frameon": False,
    "xtick.direction": "in",
    "xtick.major.size": 6,
    "xtick.minor.size": 3,
    "xtick.major.pad": 3,
    "xtick.top": True,
    "xtick.major.top": True,
    "xtick.major.bottom": True,
    "xtick.minor.top": True,
    "xtick.minor.bottom": True,
    "xtick.minor.visible": True,
    "ytick.direction": "in",
    "ytick.major.size": 6,
    "ytick.minor.size": 2.0,
    "ytick.right": True,
    "ytick.major.left": True,
    "ytick.major.right": True,
    "ytick.minor.left": True,
    "ytick.minor.right": True,
    "ytick.minor.visible": True,
    "grid.alpha": 0.8,
    "grid.linestyle": ":",
    "axes.linewidth": 2,
    "savefig.transparent": False,
    "savefig.bbox": "tight",
    "xaxis.labellocation": "right",
    "yaxis.labellocation": "top",
}

CMS = {
    "font.sans-serif": ["DejaVu Sans"],
    "font.family": "sans-serif",
    "mathtext.fontset": "custom",
    # "mathtext.rm": "Helvetica",
    # "mathtext.bf": "Helvetica:bold",
    # "mathtext.sf": "Helvetica",
    # "mathtext.it": "Helvetica:italic",
    # "mathtext.tt": "Helvetica",
    # "mathtext.cal": "Helvetica",
    "mathtext.default": "regular",
    "figure.figsize": (10.0, 10.0),
    "font.size": 26,
    "axes.labelsize": "medium",
    "axes.unicode_minus": False,
    "xtick.labelsize": "small",
    "ytick.labelsize": "small",
    "legend.fontsize": "small",
    "legend.handlelength": 1.5,
    "legend.borderpad": 0.5,
    "legend.frameon": False,
    "xtick.direction": "in",
    "xtick.major.size": 12,
    "xtick.minor.size": 6,
    "xtick.major.pad": 6,
    "xtick.top": True,
    "xtick.major.top": True,
    "xtick.major.bottom": True,
    "xtick.minor.top": True,
    "xtick.minor.bottom": True,
    "xtick.minor.visible": True,
    "ytick.direction": "in",
    "ytick.major.size": 12,
    "ytick.minor.size": 6.0,
    "ytick.right": True,
    "ytick.major.left": True,
    "ytick.major.right": True,
    "ytick.minor.left": True,
    "ytick.minor.right": True,
    "ytick.minor.visible": True,
    "grid.alpha": 0.8,
    "grid.linestyle": ":",
    "axes.linewidth": 2,
    "savefig.transparent": False,
    "xaxis.labellocation": "right",
    "yaxis.labellocation": "top",
}

# Filter extra (labellocation) items if needed
CMS = {k: v for k, v in CMS.items() if k in mpl.rcParams}
lotsa_plots = {k: v for k, v in lotsa_plots.items() if k in mpl.rcParams}

CMSTex = {
    **CMS,
    "text.usetex": True,
    "text.latex.preamble": r"\usepackage{siunitx},\sisetup{detect-all}, \
                              \usepackage{helvet},\usepackage{sansmath}, \
                              \sansmath",
}

from matplotlib.pyplot import style as plt_style
plt_style.use(CMS)