import matplotlib as mpl
# import matplotlib.font_manager

def mpoint_title(MX=700, MY=400):
    return rf"$M_X = {MX}$ GeV, $M_Y = {MY}$ GeV"

CMS = {
    "font.family": "sans-serif",
    "font.sans-serif": ["DejaVu Sans", "Helvetica", "Arial"],
    # "font.serif": ["Tahoma", "DejaVu Sans", "Helvetica", "Arial"],
    "mathtext.fontset": "custom",
    "mathtext.rm": "DejaVu Sans",
    "mathtext.bf": "DejaVu Sans:bold",
    "mathtext.sf": "DejaVu Sans",
    "mathtext.it": "DejaVu Sans:italic",
    "mathtext.tt": "DejaVu Sans",
    "mathtext.cal": "DejaVu Sans",
    "mathtext.default": "regular",
    "figure.figsize": (10.0, 10.0),
    "font.size": 20,
    "axes.labelsize": "medium",
    "axes.unicode_minus": False,
    "xtick.labelsize": "small",
    "ytick.labelsize": "small",
    "legend.fontsize": 16,
    "legend.handlelength": 1.5,
    "legend.borderpad": 0.5,
    "legend.frameon": False,
    "legend.handletextpad" : 0.3,
    "xtick.direction": "in",
    "xtick.major.size": 12,
    "xtick.minor.size": 6,
    "xtick.major.pad": 6,
    "xtick.top": True,
    "xtick.major.top": True,
    "xtick.major.bottom": True,
    "xtick.minor.top": True,
    "xtick.minor.bottom": True,
    "xtick.minor.visible": True,
    "ytick.direction": "in",
    "ytick.major.size": 12,
    "ytick.minor.size": 6.0,
    "ytick.right": True,
    "ytick.major.left": True,
    "ytick.major.right": True,
    "ytick.minor.left": True,
    "ytick.minor.right": True,
    "ytick.minor.visible": True,
    "grid.alpha": 0.8,
    "grid.linestyle": ":",
    "axes.linewidth": 1.5,
    "axes.titlesize" : "medium",
    "axes.titlepad" : 10,
    "axes.titlelocation" : "right",
    "axes.labelpad" : 6,
    "savefig.transparent": False,
    "savefig.format": "pdf",
    "xaxis.labellocation": "right",
    "yaxis.labellocation": "top",
    "savefig.bbox" : 'tight'
}

custom = {
    "font.sans-serif": ["DejaVu Sans"],
    "font.family": "DejaVu Sans",
    "mathtext.fontset": "custom",
    "mathtext.rm": "sans",
    "mathtext.bf": "DejaVu Sans:bold",
    "mathtext.sf": "DejaVu Sans",
    "mathtext.it": "DejaVu Sans:italic",
    "mathtext.tt": "DejaVu Sans",
    "mathtext.cal": "DejaVu Sans",
    "mathtext.default": "regular",
    "figure.figsize": (10.0, 10.0),
    "font.size": 24,
    "axes.labelsize": "medium",
    "axes.titlesize": "medium",
    "axes.unicode_minus": False,
    "axes.linewidth": 2,
    "axes.formatter.limits: ": (-3, 3),
    "axes.formatter.use_mathtext": True,
    "axes.formatter.min_exponent": 0,
    "axes.formatter.useoffset": True,
    "axes.formatter.offset_threshold": 3,
    "axes.titlepad": 30.0,
    "grid.alpha": 0.8,
    "grid.linestyle": ":",
    "line.linewidth": "2",
    "legend.fontsize": "small",
    "legend.handlelength": 1.5,
    "legend.borderpad": 0.5,
    "legend.frameon": False,
    "xaxis.labellocation": "right",
    "xtick.labelsize": "small",
    "xtick.direction": "in",
    "xtick.major.size": 12,
    "xtick.minor.size": 6,
    "xtick.major.pad": 6,
    "xtick.top": True,
    "xtick.top": True,
    "xtick.major.top": True,
    "xtick.major.bottom": True,
    "xtick.minor.top": True,
    "xtick.minor.bottom": True,
    "xtick.minor.visible": True,
    "xtick.minor.visible": True,
    "yaxis.labellocation": "top",
    "ytick.labelsize": "small",
    "ytick.direction": "in",
    "ytick.major.size": 12,
    "ytick.minor.size": 6.0,
    "ytick.right": True,
    "ytick.major.left": True,
    "ytick.major.right": True,
    "ytick.minor.left": True,
    "ytick.minor.right": True,
    "ytick.minor.visible": True,
    "savefig.transparent": False,
    "savefig.bbox": 'tight',
}

lotsa_plots = {
    "font.sans-serif": ["DejaVu Sans"],
    "font.family": "sans-serif",
    "mathtext.fontset": "custom",
    # "mathtext.rm": "Helvetica",
    # "mathtext.bf": "Helvetica:bold",
    # "mathtext.sf": "Helvetica",
    # "mathtext.it": "Helvetica:italic",
    # "mathtext.tt": "Helvetica",
    # "mathtext.cal": "Helvetica",
    "mathtext.default": "regular",
    "figure.figsize": (10.0, 10.0),
    "font.size": 16,
    "axes.labelsize": "medium",
    "axes.unicode_minus": False,
    "xtick.labelsize": "small",
    "ytick.labelsize": "small",
    "legend.fontsize": "small",
    "legend.handlelength": 1.5,
    "legend.borderpad": 0.5,
    "legend.frameon": False,
    "xtick.direction": "in",
    "xtick.major.size": 6,
    "xtick.minor.size": 3,
    "xtick.major.pad": 3,
    "xtick.top": True,
    "xtick.major.top": True,
    "xtick.major.bottom": True,
    "xtick.minor.top": True,
    "xtick.minor.bottom": True,
    "xtick.minor.visible": True,
    "ytick.direction": "in",
    "ytick.major.size": 6,
    "ytick.minor.size": 2.0,
    "ytick.right": True,
    "ytick.major.left": True,
    "ytick.major.right": True,
    "ytick.minor.left": True,
    "ytick.minor.right": True,
    "ytick.minor.visible": True,
    "grid.alpha": 0.8,
    "grid.linestyle": ":",
    "axes.linewidth": 2,
    "savefig.transparent": False,
    "savefig.bbox": "tight",
    "xaxis.labellocation": "right",
    "yaxis.labellocation": "top",
}

# Filter extra (labellocation) items if needed
CMS = {k: v for k, v in CMS.items() if k in mpl.rcParams}
lotsa_plots = {k: v for k, v in lotsa_plots.items() if k in mpl.rcParams}
custom = {k: v for k, v in custom.items() if k in mpl.rcParams}

CMSTex = {
    **CMS,
    "text.usetex": True,
    "text.latex.preamble": r"\usepackage{siunitx},\sisetup{detect-all}, \
                              \usepackage{helvet},\usepackage{sansmath}, \
                              \sansmath",
}
customTex = {
    **custom,
    "text.usetex": True,
    "text.latex.preamble": r"\usepackage{siunitx},\sisetup{detect-all}, \
                              \usepackage{helvet},\usepackage{sansmath}, \
                              \sansmath",
}

from matplotlib.pyplot import style as plt_style
plt_style.use(CMS)
# plt_style.use(custom)