#!/bin/sh

#SBATCH --job-name=train-count
#SBATCH --qos=avery
#SBATCH --account=avery
#SBATCH --time=4:00:00
#SBATCH --partition=hpg-dev
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8GB
#SBATCH --output=slurm_output/slurm-%A_%a.out

# sbatch scripts/feynnet/training/run

python scripts/feynnet/training/print_config.py

sh scripts/feynnet/training/submitScriptsToSLURM.sh

# python scripts/feynnet/training/plot_nevents.py

# rm tmp/*_nevents*